version: '3'
services:
  database:
    image: "postgres:12-alpine"
    restart: always
    ports:
    - 5432:5432
    environment:
      POSTGRES_DB: goodplant
      POSTGRES_USER: goodplant
      POSTGRES_PASSWORD: goodplant
#
#  backend:
#    env_file:
#      - .env
#    build:
#      context: ./
#      dockerfile: ./Dockerfile
#    working_dir: /app
#    image: backend
#    container_name: backend
#    ports:
#    - 3000:3000
#    command: sh -c "yarn dev"
#    restart: unless-stopped
#    volumes:
#    - .:/app:cached
#    depends_on:
#      - database
#    environment:
#      TZ: "UTC"
#      NODE_DEV: "true"
#      TS_NODE_PROJECT: "tsconfig.json"

